---

- name: Update apt cache 
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc

- name: Install base packages
  apt: name={{ item }} force=yes state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - python-dev
    - python-pip
    - python-pycurl
    - supervisor
    - nginx

- name: Install virtualenv
  pip: name=virtualenv